### ISSUE TITLE
HTML To-Do List

### ISSUE THREAD

**Issue by matt-martinez** [matt-martinez/blackjackattack#3]
- [x] Title h1
- [x] Dealer h2
- [x] Player h2
- [x] Board Div
- [x] Dealer Card Divs (2)
- [x] Player Card Divs (2-5)
- [x] Money Remaining h3
- [x] Player Bankroll Div
- [x] Chip Image
- [x] Bet Button
- [x] Hit Button
- [x] Hold Button
- [ ] Special Moves Buttons (Double, Split, Insurance)
- [x] New Game/Reset Game Buttons
- [x] Create three bet buttons
