### ISSUE TITLE
CSS To-Do List

### ISSUE THREAD

**Issue by matt-martinez** [matt-martinez/blackjackattack#4]
- [ ] Create Hover Effect for Buttons
- [x] Re-size card Divs
- [x]  Add styling to bet buttons
- [x] Reconfigure board layout after adding bet buttons
