### ISSUE TITLE
MVP User Stories and JS Checklist

### ISSUE THREAD

**Issue by matt-martinez** [matt-martinez/blackjackattack#5]
# Blackjack

## MVP User Stories

**As a user, I want to be able to start a new game.** 

- [x] The user sees the game title and a New Game button.

**As a user, I want to be able to enter my name to make it more personal.** 

- [x] The user presses the New Game button and receives a prompt to enter their name. 
- [x] Once the user enters their name, it is then appended to the player object within the overall game.

**As a user, I want to see how much money I have.** 

- [x] The player should see a div with the current bankroll. 
- [x] Once the user enters their name, Player should be appended to "Player Name". 
- [ ] The total dollar amount in this div should change to reflect the amount of money the player has left whenever they bet, win, or lose.

**As a user, I want to be able to bet money each hand I play in different increments.** 

- [x] The game loop will begin once the player chooses how much they want to bet for the current hand.
- [x] For this game, the player can bet in increments of $25, $50, and $100 amounts.
- [x] There will be a max bet of $100 each hand.
- [x] The user will need a way to clearly communicate to the game how much they wish to bet for each hand.

**As a user, I want to to be able to get additional cards to make 21, or hold onto what I have.** 

- [x] After placing their bet, the user will receive two cards which can have a total combined amount of 2 to 21.
- [x] Based on their current card total, the player will need to choose either to "hit", to receive additional cards to equal 21, or "hold", to keep their current hand.
- [x] Whichever decision the player makes, their will need to be an appropriate amount of divs added to the board.

**As a user, I want to know if I've gone over 21 or "bust."**

- [x] The player will be given a flash message of "bust" if their combined cards equal an amount over 21.
- [x] The current game loop will then end, and the player will need to place another bet to begin the game loop again.

**As a user, I want to know if I've won.** 

- [ ] If the player's card total is <= 21, but at an amount higher than the card total for the dealer, the player will win the current hand.
- [x] The player will see a flash message indicating that they won/beat the dealer.

**As a user, I want to know if the dealer has hit 21 or "bust."** 

- [x] The player will need to see one card displayed from the dealer's hand in order to make the decision of whether to "hit" or "hold."
- [x] After the player makes their decision, the dealer will begin to "hit" to reach 21 and beat the player's card total. 
- [x] If the dealer makes it to 21 or gains a card total higher than the player, the player then loses. 
- [x] If the dealer gains a card total higher than 21, they will "bust" and the player will win the hand.
